export const SYMBOL_LIST_REQUEST = "SYMBOL_LIST_REQUEST";
export const SYMBOL_LIST_SUCCESS = "SYMBOL_LIST_SUCCESS";
export const SYMBOL_LIST_FAILURE = "SYMBOL_LIST_FAILURE";

export const WATCH_LIST_REQUEST = "WATCH_LIST_REQUEST";
export const WATCH_LIST_SUCCESS = "WATCH_LIST_SUCCESS";
export const WATCH_LIST_FAILURE = "WATCH_LIST_FAILURE";

export const REMOVE_SYMBOL = "REMOVE_SYMBOL";

export const SORT_BY = "SORT_BY";

export const WATCH_LIST_REFRESH_REQUEST = "WATCH_LIST_REFRESH_REQUEST";
export const WATCH_LIST_REFRESH_SUCCESS = "WATCH_LIST_REFRESH_SUCCESS";
export const WATCH_LIST_REFRESH_FAILURE = "WATCH_LIST_REFRESH_FAILURE";
